name: Atom tests

on:
  push:
    branches: [ "main" ] # Trigger on push to the 'main' branch
    paths: ["**.cpp", "**.hpp", "Makefile", "atm/test/**"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository code
      uses: actions/checkout@v4

    - name: Setup C++ environment
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential
        chmod -R +r atm test

    - name: Compile program
      run: make re

    - name: Run tests
      run: |
        ./test/run_test.sh lexer
        ./test/run_test.sh parser
        ./test/run_test.sh code_gen
