name: Atom tests

on:
  push:
    branches: [ "main" ] # Trigger on push to the 'main' branch
    paths: ["**.cpp", "**.hpp", "Makefile", "atm/test/**"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository code
      uses: actions/checkout@v4

    - name: Setup C++ environment
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential
        chmod -R +r atm test

    - name: Compile program
      run: make re

    - name: Run tests
      run: |
        make run atm/test/test_01.atm
        make run atm/test/test_02.atm
        make run atm/test/test_03.atm
        make run atm/test/test_04.atm
        make run atm/test/test_05.atm
        make run atm/test/test_06.atm
        make run atm/test/test_07.atm
        make run atm/test/test_08.atm
