name: Atom tests

on:
  push:
    branches: [ "main" ] # Trigger on push to the 'main' branch
  pull_request:
    branches: [ "main" ] # Trigger on pull requests targeting the 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository code
      uses: actions/checkout@v4

    - name: Setup C++ environment
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential

    - name: Compile program
      run: make re

    - name: Run tests
      run: |
        make run atm/test/test_01.atm
