name: Custom Input Execution

on:
  workflow_dispatch:
    inputs:
      fileContent:
        description: "Content of the file to be compiled"
        required: true

jobs:
  custom_execution:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository code
      uses: actions/checkout@v4

    - name: Setup C++ environment
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential

    - name: Create input file
      run: echo "${{ inputs.fileContent }}" > program.atm

    - name: Run compilation
      run: make run f:dc program.atm
